$IP = "10.6.0.188"
$response = Invoke-RestMethod -Uri "$IP/api/temp"
Write-Host "Teplota: $($response.temperature) °C"
# $status = Invoke-RestMethod -Uri "$IP/api/status"
# Write-Host "Senzor: $($response.sensor)"
